# Generated by Django 4.1.7 on 2023-10-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor_hospital_service_specialty_tool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='rate',
            new_name='price',
        ),
    ]
