# Generated by Django 4.2.5 on 2023-10-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_rate_doctor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id_role',
        ),
    ]
