# Generated by Django 4.2.6 on 2023-10-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctor_account_hospital_account_user_account_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
