# Generated by Django 4.2.6 on 2023-10-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_admin_gender_alter_doctor_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id_doctor',
        ),
        migrations.CreateModel(
            name='Scheduler_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('id_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schedule')),
            ],
        ),
    ]
