# Generated by Django 4.2.6 on 2023-10-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_schedule_id_doctor_scheduler_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='descripe',
            new_name='describe',
        ),
        migrations.RenameField(
            model_name='specialty',
            old_name='descripe',
            new_name='describe',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialty'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days_of_week',
            field=models.IntegerField(),
        ),
    ]
