# Generated by Django 4.2.6 on 2023-11-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_descripe_doctor_describe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id_schedule',
        ),
        migrations.AddField(
            model_name='appointment',
            name='id_schedule_doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.scheduler_doctor'),
        ),
    ]
