# Generated by Django 4.2.6 on 2023-11-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_appointment_id_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
