# Generated by Django 4.2.6 on 2023-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_hospital_info_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
