# Generated by Django 4.2.6 on 2023-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_doctor_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
