# Generated by Django 4.2.6 on 2023-11-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_doctor_specialty_doctor_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/avatars/'),
        ),
    ]
