# Generated by Django 4.2.6 on 2023-11-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='icon',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='icon',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
