# Generated by Django 4.2.6 on 2023-11-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_service_icon_alter_specialty_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, choices=[('Hanoi', 'Hà Nội'), ('HoChiMinh', 'Hồ Chí Minh'), ('Danang', 'Đà Nẵng')], max_length=255, null=True),
        ),
    ]
