# Generated by Django 4.2.6 on 2023-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_doctor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, choices=[('Hanoi', 'Hà Nội'), ('HoChiMinh', 'Hồ Chí Minh'), ('Danang', 'Đà Nẵng')], max_length=255, null=True),
        ),
    ]
