# Generated by Django 4.2.6 on 2023-12-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_doctor_num_of_rating'),
        ('app', '0029_hospital_city'),
    ]

    operations = [
    ]
