# Generated by Django 4.2.6 on 2023-12-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_merge_0023_doctor_num_of_rating_0029_hospital_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
